config/routes.rb
Rails.application.routes.draw do

   get 'sign_up', to: 'users#new'
   get 'log_in', to: 'sessions#new'
   get 'log_out', to: 'sessions#destroy'
   root 'users#index'
   resources :users
   resources :sessions

end

app/models/user.rb
class User < ActiveRecord::Base
  validates_presence_of :name, :password
  validates_uniqueness_of :name

  private

  def self.authenticate(name,password)
    User.exists?(name: name,password: password)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user
  include ApplicationHelper

  

  private

  def authenticate_user
    if current_user.blank?

        if restricted_action?

       redirect_to log_in_path
      end
    end

  end

  def restricted_action?
    if controller_name == "sessions"
      ["new","create"].exclude? action_name
    elsif controller_name == "users"
      ["new","create"].exclude? action_name
    else
      true
    end
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    name = params[:session][:name]
    password = params[:session][:password]
    if  User.authenticate(name,password)
      session[:user_id] = User.find_by_name(name).id
      redirect_to users_path
    else
      session[:user_id] = nil
      redirect_to log_in_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to log_in_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to users_path
    else
      render :new
    end
  end


  private

  def user_params
    params.require(:user).permit(:name, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rspecapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <!--<a class="navbar-brand" href="#"></a> -->
        <%= link_to "RspecApp", users_path , class: 'navbar-brand' %>
      </div>
    <ul class="nav navbar-nav navbar-right ">
      <% if current_user %>
        <p class="navbar-text">Logged in as <%= current_user.name %></p>
        <li><%= link_to "Log out", log_out_path %></li>
      <% else %>
        <li><%= link_to "Sign up", sign_up_path %></li>
        <li><%= link_to "log in", log_in_path %></li>
      <% end %>
    </ul>
  </div>
</nav>
<div class="container">
  <div class="row">
    <div class="span10">
      <%= yield %>
    </div>
  </div>
</div>
</body>
</html>

app/views/users/index.html.slim
table
  th Name
  - for user in @users
    tr
      td
        = user.name

app/views/users/new.html.slim
= simple_form_for @user do |f|
  = f.input :name
  = f.input :password
  = f.button :submit, "Sign Up"